######################################################################
# Automatically generated by qmake (1.07a) Mon Oct 19 17:05:27 2009
######################################################################

# Directories
HEADERS = mainwindow.h infinite_scroll.h bible_text_source.h search_dialog.h
SOURCES = main.cpp mainwindow.cpp infinite_scroll.cpp bible_text_source.cpp \
		search_dialog.cpp
CONFIG += qt
LIBS += -lsword -lQtMaemo5
INCLUDEPATH += /usr/include/sword
